# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 08:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('birthday', models.DateTimeField()),
                ('taiwanId', models.CharField(max_length=255)),
                ('vegetarian', models.BooleanField(default=False)),
                ('contactPerson', models.CharField(max_length=255)),
                ('guardian', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('ojAccount', models.TextField()),
                ('selfIntro', models.TextField()),
                ('joinReason', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
