# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20170515_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='howToArriva',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='needStay',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
