# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170517_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='howToArriva',
            new_name='howToArrival',
        ),
    ]
